networks:
  teams-net:
    driver: bridge


volumes:
  data:
    driver: local


services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - './:/var/www'
      - ./nginx/conf.d:/etc/nginx/conf.d/
    depends_on:
      - app
      - db

  app:
    image: app
    build: 
      context: .
      dockerfile: DockerFile
    volumes:
      - ./.:/var/www
    working_dir: /var/www
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=secret
      - MYSQL_DATABASE=teams_db
      - MYSQL_USER=teams_user
      - MYSQL_PASSWORD=password